### ISSUE TITLE
NullPointerException: null 

### ISSUE THREAD

**Issue by ziceptor** [ustc-zzzz/VirtualChest#20]
forge-1.12.2-14.23.0.2486-universal.jar
spongeforge-1.12.2-2486-7.0.0-BETA-2646.jar
VirtualChest-0.3.9.jar

from fml-junk-earlystartup.log: https://gist.github.com/ziceptor/a1f2515fd568f4ace41fbdb68956192a

**Comment by ustc-zzzz** [comment]
Please provide the full log file (`logs/fml-server-latest.log`).
I believe that there is another error happened before this one.

**Comment by ziceptor** [comment]
[fml-server-latest.log](https://gist.github.com/ziceptor/b1aa33056f00403afa0d3ce20d5710a5)

**Comment by ustc-zzzz** [comment]
Maybe you have restarted your server several times.
What I need is the log in which the error of my plugin happened.
Please provide the log of your server thread around `[12:11:16]`.
Maybe it is `fml-server-x.log`, or `2017-09-22-x.log.gz`.

**Comment by ziceptor** [comment]
error [fml-junk-earlystartup.log](https://gist.github.com/ziceptor/4a580f07cbd4bf6b095710d2ad94a4c6)

**Comment by ziceptor** [comment]
an error has occurred after starting the server

**Comment by ziceptor** [comment]
fml-junk-earlystartup.log now
https://gist.github.com/ziceptor/173a1de4fba3bbce609c5ee42c8256c5

1. [18:52:31] [Server thread/ERROR] [Sponge]: Could not pass FMLPostInitializationEvent to Plugin{id=virtualchest

2. [18:52:37] [Server thread/ERROR] [Sponge]: Could not pass FMLServerStartedEvent to Plugin{id=virtualchest

3. [18:52:37] [Server thread/ERROR] [Sponge]: Could not pass FMLServerStartedEvent to Plugin{id=virtualchest

**Comment by ziceptor** [comment]
[18:52:31] [Server thread/ERROR] [Sponge]: Could not pass FMLPostInitializationEvent to Plugin{id=virtualchest, name=VirtualChest, version=0.3.9, description=A sponge plugin providing virtual chest GUIs for menus., authors=[ustc_zzzz], source=E:\ziCRAFT-1.12.2\mods\VirtualChest-0.3.9.jar}
java.lang.NoSuchMethodError: org.spongepowered.api.event.cause.Cause.source(Ljava/lang/Object;)Lorg/spongepowered/api/event/cause/Cause$Builder;

**Comment by ustc-zzzz** [comment]
Well, it looks like you are using SpongeForge 1.12.x server, whose api is v7.0.0. SpongeAPI v7.0.0 provides a completely new event cause system which breaks the backward compatibllity for plugins depending on v5.x or v6.x.
However, I'm not working on VirtualChest v0.4.0 and this problem won't be fixed at VirtualChest v0.3.x. Thanks for your attention.

**Comment by ziceptor** [comment]
When you plan to release a plugin for api7?

**Comment by ustc-zzzz** [comment]
As soon as this pull request is merged:
<https://github.com/SpongePowered/SpongeCommon/pull/1544>

**Comment by ziceptor** [comment]
Merged!

**Comment by ustc-zzzz** [comment]
SpongeForge has been updated 19 hours ago, and 1.12.x is now supported by VirtualChest.
